import { jsPDF } from "jspdf";

export const generateSpecSheet = (product) => {
  // 1. Initialize a new standard A4 document
  const doc = new jsPDF();

  // 2. Add Corporate Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(234, 88, 12); // Orange theme color
  doc.text("TECHONE HEATERS", 20, 30);

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text("Industrial Thermal Engineering | Hyderabad, India", 20, 38);

  // Divider Line
  doc.setLineWidth(0.5);
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 45, 190, 45);

  // 3. Product Title & Category
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(20, 20, 20);
  doc.text(`Specification Sheet: ${product.name}`, 20, 60);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.text(`Equipment Category: ${product.category.toUpperCase()}`, 20, 70);

  // 4. Product Description (with text wrapping)
  doc.setFont("helvetica", "bold");
  doc.text("Engineering Overview:", 20, 90);
  
  doc.setFont("helvetica", "normal");
  const splitDescription = doc.splitTextToSize(product.description, 170);
  doc.text(splitDescription, 20, 100);

  // 5. Core Features List
  let startY = 100 + (splitDescription.length * 7) + 10;
  doc.setFont("helvetica", "bold");
  doc.text("Core Technical Features:", 20, startY);
  
  doc.setFont("helvetica", "normal");
  product.features.forEach((feature, index) => {
    doc.text(`• ${feature}`, 25, startY + 10 + (index * 8));
  });

  // 6. Footer
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Techone Heaters Digital Systems. All dimensions and specs are subject to change.", 20, 280);

  // 7. Trigger the Download!
  doc.save(`${product.id}-spec-sheet.pdf`);
};